#!/bin/bash
clear
wmctrl -r :ACTIVE: -N "Applying Build Settings"
NOW=$(date +"%d-%m-%Y")
echo "Current Date : $NOW"
echo "Applying Build Settings"
sleep 1

#CONFIGS
echo "Setting ARM Arch"
export ARCH=arm
echo "Setting Defconfig"
export DEFCONFIG=cyanogenmod_x909_defconfig
echo "Setting Date And Time For Zip File"
export NOW=$(date +"%d-%m-%Y")
echo "Setting Toolchain"
export GCC=AK-linaro
echo "Setting Toolchain Version"
export VER=4.9.3-2015.02.20150221.CR83
echo "Setting Toolchain Location"
export TOOLCHAIN=../$GCC/$VER/bin/arm-eabi-
echo "Setting Toolchain Strip Location"
export TSTRIP=`pwd`/../$GCC/bin/arm-linux-androideabi-strip
echo "Setting Strip Arguments"
export STRIP=--strip-unneeded
echo "Setting CPU Cores/Threads"
export CPUS=`nproc`
echo "Setting zImage Location For Infinitus-Dev kernel"
export ZIMAGE=arch/arm/boot/zImage
echo "Enabling Graphite Optimizations"
export ENABLE_GRAPHITE=true
echo "Enviroment Setup Complete Now Moving To Compiling"

#Build
echo "Cleaning Out Compiled Files"
sleep 1
make clean
wmctrl -r :ACTIVE: -N "Starting Build Process"
echo "Starting Build Process"
export USE_CCACHE=1
sleep 1
if [ -f .config ];
then
   echo ".config exists"
   echo "Continuing To Compiler"
   sleep 1
else
   echo ".config Does Not Exists"
   echo "Compiling From $TOOLCHAIN $DEFCONFIG"
   make ARCH=$ARCH CROSS_COMPILE=$TOOLCHAIN $DEFCONFIG
   sleep 1
fi
wmctrl -r :ACTIVE: -N "Compiling Infinitus-Dev Kernel"
make ARCH=$ARCH CROSS_COMPILE=$TOOLCHAIN -j$CPUS

if [ -f $ZIMAGE ];
then
   echo "$ZIMAGE exists"
   echo "Compile Complete Continuing To Stripping"
   sleep 1
else
   echo "$ZIMAGE Does Not Exists Please Check For Compile Errors"
   echo "Now exiting script"
   sleep 1
   exit 0
fi

#Infinitus-Dev Kernel Packing
wmctrl -r :ACTIVE: -N "Infinitus-Dev Kernel Packing"
echo "Starting Packing To Recovery Flashable Zip"
cd packer-find5/
echo "Removing Old Files"
rm -rf kernel/zImage
sleep 1
echo "Copying zImage"
find '../arch/' -name "zImage" -exec cp -av {} kernel/ \;
sleep 1
echo "Compiling Infinitus-Dev-Kernel-LP-"$NOW".zip"
zip -r Infinitus-Dev-Kernel-Find5-LP-"$NOW".zip kernel/ META-INF/ system/
sleep 1
echo "Signing Zip"
java -classpath testsign.jar testsign Infinitus-Dev-Kernel-Find5-LP-"$NOW".zip Infinitus-Dev-Kernel-Find5-LP-"$NOW"-Signed.zip
sleep 1
echo "Renamed Infinitus-Dev-Kernel-Find5-LP-"$NOW"-Signed.zip To Infinitus-Dev-Kernel-Find5-LP-"$NOW".zip"
mv Infinitus-Dev-Kernel-Find5-LP-"$NOW"-Signed.zip Infinitus-Dev-Kernel-Find5-LP-"$NOW".zip && rm kernel/zImage
sleep 1
echo "Completed Builing Infinitus-Dev-Kernel-Find5-LP-"$NOW".zip"
sleep 1
echo "Look In The Packer-Find5 Folder For Infinitus-Dev-Kernel-Find5-LP-"$NOW".zip And Flash It ;)"
wmctrl -r :ACTIVE: -N "Terminal"
nowf=$(date +"%T")
echo "Completion Time : $nowf"
